
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const ApplicationSelector = lazy(() => import("./pages/ApplicationSelector.tsx"));
const ConnectionConfig = lazy(() => import("./pages/ConnectionConfig.tsx"));
const DatabaseSchemaViewer = lazy(() => import("./pages/DatabaseSchemaViewer.tsx"));
const MigrationDashboard = lazy(() => import("./pages/MigrationDashboard.tsx"));
const MigrationExecution = lazy(() => import("./pages/MigrationExecution.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/application-selector", element: <ApplicationSelector />},
	{ path: "/applicationselector", element: <ApplicationSelector />},
	{ path: "/connection-config", element: <ConnectionConfig />},
	{ path: "/connectionconfig", element: <ConnectionConfig />},
	{ path: "/database-schema-viewer", element: <DatabaseSchemaViewer />},
	{ path: "/databaseschemaviewer", element: <DatabaseSchemaViewer />},
	{ path: "/migration-dashboard", element: <MigrationDashboard />},
	{ path: "/migrationdashboard", element: <MigrationDashboard />},
	{ path: "/migration-execution", element: <MigrationExecution />},
	{ path: "/migrationexecution", element: <MigrationExecution />},

];
